#!/bin/bash
start() {
  killall sslocal
  nohup sslocal -c /root/tools/shadow_privoxy/shadowsocksCong.json &
  if [ $? -ne 0 ];then
    echo "start error"
    exit
  fi
  sed -i "/forward-socks5 \/ 127.0.0.1:1080 \./d" /etc/privoxy/config
  echo "forward-socks5 / 127.0.0.1:1080 ." >> /etc/privoxy/config
  service privoxy start
  echo "export http_proxy=http://127.0.0.1:8118" >> /etc/environment
  echo "export https_proxy=http://127.0.0.1:8118" >> /etc/environment
  source /etc/environment
}

stop() {
  killall sslocal
  sed -i '/http_proxy/d' /etc/environment
  sed -i '/https_proxy/d' /etc/environment
  source /etc/environment
  sed -i "/\#forward-socks5 \/ 127.0.0.1:1080 \./d" /etc/privoxy/config
  sed -i "/forward-socks5 \/ 127.0.0.1:1080 \./d" /etc/privoxy/config
  service privoxy stop
  echo "close shadowsocks"
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    ;;
esac
